stages:
  - build
  - deploy

build-job-test:
  image: node:12-alpine
  stage: build
  tags:
    - angular
  before_script:
    - apk add zip
  script:
    - npm link @angular/cli
    - cd timebank
    - npm install
    - npm run build
    - cd dist/timebank
    - zip -r test.zip *
    - mv test.zip ../../../test.zip
  artifacts:
    paths:
      - test.zip
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull

build-job-prod:
  image: node:12-alpine
  stage: build
  tags:
    - angular
  before_script:
    - apk add zip
  script:
    - npm link @angular/cli
    - cd timebank
    - npm install
    - npm run build environment=production
    - cd dist/timebank
    - zip -r prod.zip *
    - mv prod.zip ../../../prod.zip
  artifacts:
    paths:
      - prod.zip
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull

deploy-to-test-job:
  stage: deploy
  tags:
    - angular
  needs: ['build-job-test']
  before_script:
  - apk add unzip
  - apk add openssh-client
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no automation@157.245.27.101 " rm -r /var/www/html/*"
    - scp -o StrictHostKeyChecking=no test.zip automation@157.245.27.101:/var/www/html
    - ssh -o StrictHostKeyChecking=no automation@157.245.27.101 "cd /var/www/html; unzip test.zip"
    - ssh -o StrictHostKeyChecking=no automation@157.245.27.101 "cd /var/www/html; rm test.zip"
    - echo "Build for test finished"

deploy-to-prod-job:
  stage: deploy
  tags:
    - angular
  needs: ['deploy-to-test-job', 'build-job-prod']
  when: manual
  before_script:
  - apk add unzip
  - apk add openssh-client
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no automation@157.230.79.85 " rm -r /var/www/html/*"
    - scp -o StrictHostKeyChecking=no prod.zip automation@157.230.79.85:/var/www/html
    - ssh -o StrictHostKeyChecking=no automation@157.230.79.85 "cd /var/www/html; unzip prod.zip"
    - ssh -o StrictHostKeyChecking=no automation@157.230.79.85 "cd /var/www/html; rm prod.zip"
    - echo "Build for prod finished"
